version: '3.0'

services:
  grafana:
    container_name: 'testorg-image-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/testorg-image-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
  
